⚙️Servo motor code for ESP32-S3
ABC-practica-2024/BlackPearl pull request #11
Opened 2024-08-07 16:33 UTC by Meka04

A code that rotates the servo motor from 30 to 150 degrees, and backwards.

2024-08-08 08:05 UTC, haloandrei requested changes

2024-08-08 08:05 UTC, haloandrei commented on Firmware/ESP32S3_Servo_Sweep
Asta nu e un fisier de cod, ai adaugat un fisier binar. Incearca sa adaugi codul scris in C

2024-08-08 08:06 UTC, haloandrei commented
Adauga un emoji descriptiv ca prim caracter al titlului PR-ului. [Check this PR](https://github.com/ABC-practica-2024/BlackPearl/pull/6)

2024-08-08 10:53 UTC, AporSzakacs approved these changes
crazy

2024-08-16 09:57 UTC, Andreescu-Arthur approved these changes

2024-08-16 10:18 UTC, 912-Cseke-Stefan approved these changes

2024-08-16 15:56 UTC, haloandrei approved these changes

2024-08-16 15:56 UTC, haloandrei commented
@Meka04 Green Light to merge when you are ready

2024-08-20 08:35 UTC, merged